// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).

import { SomeObj, Versions } from "./electron/preload/pre-types";

declare global {
  declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  declare const MAIN_WINDOW_VITE_NAME: string;
  const versions: typeof Versions
  const someObj: typeof SomeObj

  // interface Window { versions: typeof Versions }
}

